% TODO: rename it  
function Uxy_o  = calc_dot( ...
        x_m,                ...
        y_m,                ...
        zone_number,        ...     
        lambda_m,           ...
        focus_dist_m,       ...
        rho_min_m,          ...
        rho_max_m,          ...
        phi_step_rad,       ...  % angle step of  cur zone TODO: make a better comment
        rho_step_m,         ...     % radius_step_m,
        phi_cnt,            ...
        rho_cnt             ...
        );

    Uxy = 0;
    const_A = 1/(lambda_m*focus_dist_m);
    const_B = -1i*2*pi/lambda_m;
    rho_m   = rho_min_m:rho_step_m:rho_max_m;
    phi_rad = 0:phi_step_rad:2*pi;
    r01 = @( phi_rad, rho_m ) sqrt( focus_dist_m^2 + ( x_m - rho_m.*cos(phi_rad) ).^2 + ( y_m - rho_m.*sin(phi_rad) ).^2 );

    [RHO, PHI] = meshgrid(rho_m, phi_rad);

    Uxy = const_A*exp(const_B.*r01(PHI, RHO)).*RHO;
    Uxy_o =  trapz(rho_m, trapz(phi_rad,Uxy, 2));
end
