% TODO: rename it  
% TODO: make a comments of function arguments 
function Uxy_o  = calc_dot( ...
        x_m,                ...
        y_m,                ...
        zone_number,        ...     
        lambda_m,           ...
        focus_dist_m,       ...
        rho_min_m,          ...
        rho_max_m,          ...
        phi_step_rad,       ...  
        rho_step_m,         ... 
        phi_cnt,            ...
        rho_cnt,            ...
        gamma_rad           ...
        );


    % constants :    
    const_A = 1/(lambda_m*focus_dist_m);
    const_B = -1i*2*pi/lambda_m;

    % funcions :
    r01 = @( phi_rad, rho_m ) sqrt( focus_dist_m^2 + ( x_m - rho_m.*cos(phi_rad) ).^2 + ( y_m - rho_m.*sin(phi_rad) ).^2 );

    % arrays :
    rho_m   = rho_min_m:rho_step_m:rho_max_m;
    phi_rad = 0:phi_step_rad:2*pi;
    [RHO, PHI] = meshgrid(rho_m, phi_rad);


    Uxy   = const_A*exp(const_B.*r01(PHI, RHO)).*RHO;
    Uxy   = Uxy.*exp(-const_B.*RHO.*cos(PHI).*sin(gamma_rad));
    Uxy_o = trapz(phi_rad, trapz(rho_m,Uxy, 2));
end
